project_id = "bmlxazcllmoupkjzrrnl"

[functions.generate-baseline]
verify_jwt = true

[functions.collect-articles-for-tracking]
verify_jwt = false

[functions.research-fighter-comparison]
verify_jwt = false

[functions.reset-research-data]
verify_jwt = true

[functions.suggest-dimension-weights]
verify_jwt = false

[functions.generate-strategic-suggestions]
verify_jwt = false

[functions.generate-blackhat-analysis]
verify_jwt = false