project_id = "bmlxazcllmoupkjzrrnl"

[functions.generate-baseline]
verify_jwt = true

[functions.collect-articles-for-tracking]
verify_jwt = true

[functions.research-fighter-comparison]
verify_jwt = true

[functions.reset-research-data]
verify_jwt = true

[functions.suggest-dimension-weights]
verify_jwt = true

[functions.generate-strategic-suggestions]
verify_jwt = true

[functions.generate-blackhat-analysis]
verify_jwt = true

[functions.agent-discover-outlets]
verify_jwt = true

[functions.agent-monitor-news]
verify_jwt = true

[functions.generate-background-analysis]
verify_jwt = true

[functions.generate-media-outlets]
verify_jwt = true

[functions.analyze-sentiment]
verify_jwt = true

[functions.collect-social-media]
verify_jwt = true

[functions.search-fighter-articles]
verify_jwt = true

[functions.search-recent-media-references]
verify_jwt = true